# Generated by Django 4.2.7 on 2023-11-20 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(choices=[('Credit Card', 'Credit Card'), ('Cash on Delivery', 'Cash on Delivery'), ('Paypal', 'Paypal')], default='Credit Card', max_length=20)),
                ('status', models.CharField(choices=[('Shipping', 'Shipping'), ('Delivery', 'Delivery'), ('Prepare', 'Prepare')], default='Prepare', max_length=20)),
                ('total_amount', models.FloatField(default=0)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ku_market_place.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(default='Unisex', max_length=10)),
                ('masterCategory', models.CharField(blank=True, max_length=50)),
                ('subCategory', models.CharField(blank=True, max_length=50)),
                ('articleType', models.CharField(blank=True, max_length=50)),
                ('baseColour', models.CharField(blank=True, max_length=50)),
                ('season', models.CharField(blank=True, max_length=20)),
                ('year', models.IntegerField(blank=True, default=2023)),
                ('usage', models.CharField(blank=True, max_length=20)),
                ('productDisplayName', models.CharField(blank=True, max_length=255)),
                ('productPrice', models.FloatField(default=0.0)),
                ('quantity', models.IntegerField(default=100)),
                ('image', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ku_market_place.customer')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ku_market_place.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('total_amount', models.FloatField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ku_market_place.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_item_id',
            field=models.ManyToManyField(to='ku_market_place.orderitem'),
        ),
    ]
