# Generated by Django 4.2.5 on 2023-11-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ku_market_place", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
