# Generated by Django 4.2.7 on 2023-11-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ku_market_place', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
    ]
