# Generated by Django 4.2.5 on 2023-11-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ku_market_place", "0002_alter_customer_email"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="category_id",),
        migrations.AlterField(
            model_name="customer", name="email", field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(name="Category",),
    ]
