# Generated by Django 4.2.7 on 2023-11-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ku_market_place', '0002_alter_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('Credit Card', 'Credit Card'), ('Cash on Delivery', 'Cash on Delivery'), ('Paypal', 'Paypal')], default='Credit Card', max_length=20),
        ),
    ]
