# Generated by Django 4.2.7 on 2023-11-17 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ku_market_place', '0004_alter_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='subtotal',
        ),
    ]
