# Generated by Django 4.2.7 on 2023-11-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ku_market_place", "0004_alter_customer_email"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="description",),
        migrations.RemoveField(model_name="product", name="price",),
        migrations.RemoveField(model_name="product", name="product_name",),
        migrations.RemoveField(model_name="product", name="quantity",),
        migrations.AddField(
            model_name="product",
            name="articleType",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="product",
            name="baseColour",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="product",
            name="gender",
            field=models.CharField(default="Unisex", max_length=10),
        ),
        migrations.AddField(
            model_name="product",
            name="masterCategory",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="product",
            name="productDisplayName",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="season",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="product",
            name="subCategory",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="product",
            name="usage",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="product",
            name="year",
            field=models.IntegerField(blank=True, default=2023),
        ),
    ]
