# Generated by Django 4.2.7 on 2023-11-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ku_market_place",
            "0005_remove_product_description_remove_product_price_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="productPrice",
            field=models.FloatField(default=0.0),
        ),
    ]
