# Generated by Django 4.2.7 on 2023-11-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ku_market_place", "0006_product_productprice"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.IntegerField(default=100),
        ),
    ]
