# Generated by Django 4.2.7 on 2023-11-18 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ku_market_place', '0005_remove_orderitem_subtotal'),
        ('ku_market_place', '0007_product_quantity'),
    ]

    operations = [
    ]
