# Generated by Django 4.2.7 on 2023-11-18 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ku_market_place', '0008_merge_20231118_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_id',
            new_name='product',
        ),
    ]
