# Generated by Django 4.2.7 on 2023-11-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ku_market_place", "0008_merge_20231119_1124"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
