# Generated by Django 4.2.7 on 2023-11-19 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ku_market_place', '0012_remove_customer_password_alter_customer_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='lastname',
        ),
    ]
