# Generated by Django 4.2.7 on 2023-11-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ku_market_place', '0013_remove_customer_email_remove_customer_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Shipping', 'Shipping'), ('Delivery', 'Delivery'), ('Complete', 'Complete')], default='Shipping', max_length=20),
        ),
    ]
