# Generated by Django 4.2.7 on 2023-11-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ku_market_place', '0014_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
    ]
