# Generated by Django 4.2.7 on 2023-11-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ku_market_place', '0015_alter_orderitem_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_item_id',
        ),
        migrations.AddField(
            model_name='order',
            name='order_item_id',
            field=models.ManyToManyField(to='ku_market_place.orderitem'),
        ),
    ]
